### ISSUE TITLE
How to get anything else file drop from other app?

### ISSUE THREAD

**Issue by gemlongman** [Bunny83/UnityWindowsFileDrag-Drop#11]
For example, I drag a png form a chat windows, and drop it in Unity. 
Seems  lParam.message != WM.DROPFILES , so cannot callback.

**Comment by Bunny83** [comment]
You can't with this method. The WM_DROPFILES window message is a quite ancient API in windows. Actual drag and drop data requires much more lowlevel interaction with the windows API and it will be difficult to actually set this up since we don't really own the window that the Unity player creates. With message hooks we can hook into certain things but this has limits.

Generic drag and drop operations in windows are handled through [OLE](https://en.wikipedia.org/wiki/Object_Linking_and_Embedding) interfaces that you have to implement and [register](https://learn.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-registerdragdrop?redirectedfrom=MSDN). Specifically the [IDropTarget interface](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.idroptarget?view=windowsdesktop-8.0).

Handling generic drag and drop data also requires you to look at the various data formats that could be provided. I haven't yet done something like that in Unity or plain C# (without Forms). So I can't really help you with that at the moment :)
