### ISSUE TITLE
Not work built by Window(IL2cpp)

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [Bunny83/UnityWindowsFileDrag-Drop#4]

**Comment by Bunny83** [comment]
Well, issue is that IL2CPP can not marshal callback delegates that point to instance methods. This is most likely an issue due to managed memory so the system can not guarantee the persistance of the callback method or it simply can not map an instance method due to the implicit object reference.

I've fixed the class by turning the callbacks into static methods. Those methods also needed the "AOT.MonoPInvokeCallback" attribute. Since almost everything about the UnityDragAndDropHook class now need to be static as well, I turned the whole class into a static class. I've updated the example usage accordingly.

Tested with Unity 2019.1.10f1. I created a build with Mono as well as IL2CPP and both seem to work again.

Thanks for the IL2CPP test.
